"""Configuration and constants for the Security+ learning application."""

# Known words hashmap - A2 to C2 level common English words (expanded)
KNOWN_WORDS = {
    # A1-A2 Basic
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
    "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
    "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
    "or", "an", "will", "my", "one", "all", "would", "there", "their",
    "what", "so", "up", "out", "if", "about", "who", "get", "which", "go",
    "me", "when", "make", "can", "like", "time", "no", "just", "him", "know",
    "take", "people", "into", "year", "your", "good", "some", "could", "them",
    "see", "other", "than", "then", "now", "look", "only", "come", "its", "over",
    "think", "also", "back", "after", "use", "two", "how", "our", "work", "first",
    "well", "way", "even", "new", "want", "because", "any", "these", "give", "day",
    "most", "us", "is", "was", "are", "been", "has", "had", "were", "said", "did",
    
    # B1-B2 Intermediate
    "through", "where", "much", "before", "move", "right", "boy", "old", "too",
    "same", "tell", "does", "set", "three", "must", "air", "well", "also", "play",
    "small", "end", "put", "home", "read", "hand", "port", "large", "spell", "add",
    "even", "land", "here", "must", "big", "high", "such", "follow", "act", "why",
    "ask", "men", "change", "went", "light", "kind", "off", "need", "house", "picture",
    "try", "again", "animal", "point", "mother", "world", "near", "build", "self",
    "earth", "father", "head", "stand", "own", "page", "should", "country", "found",
    "answer", "school", "grow", "study", "still", "learn", "plant", "cover", "food",
    "sun", "four", "between", "state", "keep", "eye", "never", "last", "let", "thought",
    "city", "tree", "cross", "farm", "hard", "start", "might", "story", "saw", "far",
    "sea", "draw", "left", "late", "run", "while", "press", "close", "night", "real",
    "life", "few", "north", "book", "carry", "took", "science", "eat", "room", "friend",
    "began", "idea", "fish", "mountain", "stop", "once", "base", "hear", "horse", "cut",
    "sure", "watch", "color", "face", "wood", "main", "open", "seem", "together", "next",
    "white", "children", "begin", "got", "walk", "example", "ease", "paper", "group",
    "always", "music", "those", "both", "mark", "often", "letter", "until", "mile",
    "river", "car", "feet", "care", "second", "enough", "plain", "girl", "usual", "young",
    "ready", "above", "ever", "red", "list", "though", "feel", "talk", "bird", "soon",
    
    # C1-C2 Advanced
    "however", "therefore", "furthermore", "moreover", "nevertheless", "consequently",
    "subsequently", "accordingly", "hence", "thus", "whereas", "whereby", "wherein",
    "although", "though", "despite", "notwithstanding", "regardless", "concerning",
    "regarding", "pertaining", "considering", "given", "provided", "unless", "whether",
    "neither", "either", "both", "rather", "instead", "otherwise", "meanwhile",
    "furthermore", "additionally", "likewise", "similarly", "conversely", "alternatively",
    "specifically", "particularly", "especially", "notably", "significantly",
    "essentially", "basically", "fundamentally", "primarily", "mainly", "chiefly",
    "predominantly", "largely", "generally", "typically", "normally", "usually",
    "commonly", "frequently", "occasionally", "rarely", "seldom", "hardly", "scarcely",
    "barely", "merely", "simply", "purely", "solely", "exclusively", "entirely",
    "completely", "totally", "absolutely", "definitely", "certainly", "undoubtedly",
    "obviously", "clearly", "evidently", "apparently", "seemingly", "presumably",
    "supposedly", "allegedly", "reportedly", "arguably", "conceivably", "potentially",
    "possibly", "probably", "likely", "unlikely", "impossible", "inevitable",
    "necessary", "essential", "crucial", "vital", "critical", "important", "significant",
    "substantial", "considerable", "extensive", "comprehensive", "thorough", "detailed",
    "specific", "particular", "individual", "separate", "distinct", "unique", "special",
    "exceptional", "extraordinary", "remarkable", "notable", "outstanding", "prominent",
    "distinguished", "eminent", "renowned", "famous", "celebrated", "acclaimed",
    
    # Common verbs (all levels)
    "access", "achieve", "acquire", "adapt", "address", "adjust", "administer", "adopt",
    "advance", "affect", "allocate", "allow", "alter", "analyze", "anticipate", "apply",
    "approach", "approve", "arrange", "assess", "assign", "assist", "assume", "assure",
    "attach", "attain", "attempt", "attend", "attract", "authorize", "avoid", "balance",
    "benefit", "calculate", "capture", "cause", "challenge", "clarify", "classify",
    "collaborate", "collect", "combine", "communicate", "compare", "compete", "compile",
    "complete", "comply", "compose", "compute", "conceive", "concentrate", "conclude",
    "conduct", "configure", "confirm", "connect", "consider", "consist", "consolidate",
    "construct", "consult", "contain", "continue", "contribute", "control", "convert",
    "coordinate", "correct", "correspond", "create", "decide", "declare", "decrease",
    "define", "deliver", "demonstrate", "depend", "deploy", "describe", "design",
    "detect", "determine", "develop", "devise", "diagnose", "differentiate", "direct",
    "discover", "discuss", "display", "distribute", "document", "dominate", "draft",
    "eliminate", "emphasize", "enable", "encounter", "encourage", "enforce", "engage",
    "enhance", "ensure", "establish", "estimate", "evaluate", "examine", "exceed",
    "execute", "exhibit", "exist", "expand", "expect", "experience", "explain", "explore",
    "express", "extend", "facilitate", "feature", "focus", "follow", "forecast", "form",
    "formulate", "function", "generate", "govern", "grant", "guarantee", "guide", "handle",
    "highlight", "identify", "illustrate", "implement", "imply", "impose", "improve",
    "include", "incorporate", "increase", "indicate", "influence", "inform", "initiate",
    "innovate", "inspect", "install", "integrate", "interact", "interpret", "introduce",
    "investigate", "involve", "isolate", "issue", "justify", "launch", "lead", "leverage",
    "limit", "link", "locate", "maintain", "manage", "manipulate", "manufacture", "match",
    "maximize", "measure", "mediate", "migrate", "minimize", "modify", "monitor", "motivate",
    "navigate", "negotiate", "notify", "observe", "obtain", "occur", "operate", "optimize",
    "organize", "orient", "originate", "outline", "overcome", "oversee", "participate",
    "perceive", "perform", "permit", "persist", "persuade", "plan", "predict", "prepare",
    "present", "preserve", "prevent", "prioritize", "proceed", "process", "produce",
    "program", "progress", "project", "promote", "propose", "protect", "prove", "provide",
    "publish", "purchase", "pursue", "qualify", "quantify", "query", "question", "react",
    "realize", "receive", "recognize", "recommend", "record", "recover", "reduce", "refer",
    "reflect", "reform", "refuse", "regard", "register", "regulate", "reinforce", "reject",
    "relate", "release", "rely", "remain", "remove", "render", "repair", "repeat", "replace",
    "report", "represent", "request", "require", "research", "reserve", "resolve", "respond",
    "restore", "restrict", "result", "retain", "retrieve", "return", "reveal", "review",
    "revise", "satisfy", "save", "schedule", "search", "secure", "seek", "select", "send",
    "separate", "serve", "settle", "share", "shift", "show", "signal", "simplify", "simulate",
    "solve", "sort", "source", "specify", "sponsor", "stabilize", "standardize", "state",
    "stimulate", "store", "strengthen", "stress", "structure", "submit", "substitute",
    "succeed", "suffer", "suggest", "summarize", "supervise", "supplement", "supply",
    "support", "suppose", "suppress", "sustain", "switch", "symbolize", "synthesize",
    "target", "teach", "terminate", "test", "trace", "track", "train", "transfer",
    "transform", "translate", "transmit", "transport", "treat", "trigger", "understand",
    "undertake", "unify", "update", "upgrade", "utilize", "validate", "vary", "verify",
    "view", "violate", "visualize", "warrant", "yield",
    
    # Common adjectives
    "able", "active", "actual", "additional", "adequate", "advanced", "adverse",
    "alternative", "apparent", "applicable", "appropriate", "approximate", "arbitrary",
    "available", "average", "aware", "basic", "beneficial", "brief", "broad", "capable",
    "central", "certain", "clear", "common", "comparable", "compatible", "competitive",
    "complete", "complex", "comprehensive", "concurrent", "consistent", "constant",
    "continuous", "conventional", "correct", "critical", "crucial", "current", "dependent",
    "different", "difficult", "direct", "distinct", "diverse", "dominant", "due", "dynamic",
    "effective", "efficient", "electronic", "eligible", "equal", "equivalent", "essential",
    "evident", "exact", "excessive", "exclusive", "existing", "explicit", "external",
    "extreme", "fair", "false", "familiar", "feasible", "final", "financial", "fixed",
    "flexible", "formal", "former", "frequent", "full", "fundamental", "general", "global",
    "great", "heavy", "high", "ideal", "identical", "immediate", "implicit", "important",
    "impossible", "inadequate", "inappropriate", "independent", "individual", "inevitable",
    "inferior", "infinite", "initial", "innovative", "insufficient", "integral", "internal",
    "invalid", "joint", "key", "large", "leading", "legal", "legitimate", "likely", "limited",
    "local", "logical", "long", "low", "major", "manual", "maximum", "mental", "minimal",
    "minimum", "minor", "mobile", "modern", "multiple", "mutual", "natural", "necessary",
    "negative", "new", "next", "normal", "notable", "novel", "numerous", "objective",
    "obvious", "official", "ongoing", "open", "optimal", "optional", "original", "overall",
    "parallel", "partial", "particular", "passive", "past", "permanent", "personal",
    "physical", "positive", "possible", "potential", "practical", "precise", "preliminary",
    "present", "previous", "primary", "principal", "prior", "private", "probable",
    "professional", "progressive", "prominent", "proper", "proportional", "proposed",
    "public", "pure", "qualified", "quick", "random", "rapid", "rare", "rational", "real",
    "reasonable", "recent", "reciprocal", "redundant", "regular", "related", "relative",
    "relevant", "reliable", "remote", "representative", "required", "respective",
    "responsible", "restricted", "reverse", "right", "rigid", "robust", "routine", "safe",
    "same", "secondary", "secure", "selective", "separate", "sequential", "serious",
    "severe", "short", "significant", "similar", "simple", "single", "small", "social",
    "sole", "solid", "sophisticated", "special", "specific", "stable", "standard",
    "static", "strategic", "strict", "strong", "structural", "subsequent", "substantial",
    "successful", "successive", "sufficient", "suitable", "superior", "supplementary",
    "sure", "sustainable", "systematic", "technical", "temporary", "theoretical", "total",
    "traditional", "true", "typical", "ultimate", "unable", "uncertain", "unclear",
    "underlying", "uniform", "unique", "universal", "unknown", "unlikely", "unnecessary",
    "unprecedented", "unreasonable", "unstable", "unusual", "upper", "urgent", "useful",
    "usual", "valid", "valuable", "variable", "various", "vast", "verbal", "viable",
    "virtual", "visible", "visual", "vital", "volatile", "voluntary", "vulnerable",
    "weak", "whole", "wide", "willing", "worth", "wrong",
}
